# Generated by Django 3.2.9 on 2021-11-21 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('song', models.FileField(blank=True, upload_to='hits/songs')),
                ('cover', models.FileField(blank=True, upload_to='hits/covers')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('collaborators', models.ManyToManyField(through='hits.Collaboration', to='users.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='collaboration',
            name='hit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hits.hit'),
        ),
    ]
