# Generated by Django 3.2.9 on 2021-11-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('song', models.FileField(upload_to='hits/songs')),
                ('cover', models.FileField(upload_to='hits/covers')),
                ('colaborators', models.ManyToManyField(to='users.Artist')),
            ],
        ),
    ]
