# Generated by Django 3.2.9 on 2021-11-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hits', '0002_collaboration_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration',
            name='song',
            field=models.FileField(blank=True, upload_to='hits/collaborations/'),
        ),
    ]
